### ISSUE TITLE
Github Actions Workflow Error

### ISSUE THREAD

**Issue by mike-ward** [microsoft/infersharp#49]
Repository: https://github.com/mike-ward/Loon

```
Run microsoft/infersharpaction@v1.0
/usr/bin/docker run --name e4a64ec07f510942839d8c19711ac276e2_fa50e8 --label 5588e4 --workdir /github/workspace --rm -e DOTNET_ROOT -e INPUT_BINARY-PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Loon/Loon":"/github/workspace" 5588e4:a64ec07f510942839d8c19711ac276e2  "./src/Loon/bin/Release/net5.0"
Running Infer#...
Unable to parse instruction Castclass
Unable to parse instruction Castclass
Method with duplicate full name found: System.Void Avalonia.Themes.Default.DefaultTheme::!XamlIlPopulateTrampoline(Avalonia.Themes.Default.DefaultTheme)
Unable to parse instruction Castclass
Unable to parse instruction Castclass
Unable to parse instruction Ldftn
Unable to parse instruction Castclass
Unable to parse instruction Castclass
Unable to parse instruction Ldftn
Unable to parse instruction Castclass
Unable to parse instruction Castclass
Unable to parse instruction Ldftn
Unable to parse instruction Castclass
Unable to parse instruction Castclass
Unable to parse instruction Ldftn
Unable to parse instruction Castclass
Unable to parse instruction Castclass
Unable to parse instruction Ldftn
Unable to parse instruction Castclass
Unable to parse instruction Throw
Unable to parse instruction Throw
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Unable to cast object of type 'Mono.Cecil.ParameterDefinition' to type 'System.Int32'.
   at Cilsil.Cil.Parsers.LdargParser.ParseCilInstructionInternal(Instruction instruction, ProgramState state) in /app/Cilsil/Cil/Parsers/LdargParser.cs:line 21
   at Cilsil.Cil.Parsers.InstructionParser.ParseCilInstruction(Instruction instruction, ProgramState state) in /app/Cilsil/Cil/Parsers/InstructionParser.cs:line 83
   at Cilsil.Services.CfgParserService.ComputeMethodCfg(MethodDefinition method) in /app/Cilsil/Services/CfgParserService.cs:line 113
   at Cilsil.Services.CfgParserService.Execute() in /app/Cilsil/Services/CfgParserService.cs:line 51
   at Cilsil.Services.CfgParserService.ExecuteFromResult(ServiceExecutionResult result) in /app/Cilsil/Services/CfgParserService.cs:line 73
   at Cilsil.Services.ServiceExecutionResult.ThenExecute(IService service) in /app/Cilsil/Services/Results/ServiceExecutionResult.cs:line 11
   at Cilsil.Program.ExecuteTranslation(String[] paths, String printprocs) in /app/Cilsil/Program.cs:line 124
   at Cilsil.Program.Translate(String[] paths, String printprocs, String outcfg, String cfgtxt, String outtenv, String dot) in /app/Cilsil/Program.cs:line 95
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass2_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__16_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__14_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<<UseExceptionHandler>b__0>d.MoveNext()
You may see 'Unable to parse instruction xxx' above. This is expected as we have not yet translated all the CIL instructions, which follow a long tail distribution. We are continuing to expand our .NET translation coverage. 

Translation completed. Analyzing...

Logs in /github/workspace/infer-out/logs
Uncaught Internal Error: (Sys_error "/github/workspace/tenv.json: No such file or directory")
Error backtrace:
Raised by primitive operation at Stdlib.open_in_gen in file "stdlib.ml", line 398, characters 28-54
Called from Stdlib.open_in in file "stdlib.ml" (inlined), line 403, characters 2-45
Called from Yojson.Safe.from_file in file "lib/read.mll", line 1135, characters 13-25
Called from Backend__InferAnalyzeJson.analyze_json in file "src/backend/InferAnalyzeJson.ml", line 677, characters 24-57
Called from Integration__Driver.execute_analyze_json in file "src/integration/Driver.ml", line 177, characters 6-54
Called from IBase__Utils.timeit in file "src/base/Utils.ml", line 429, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml", line 79, characters 29-44
Called from Dune__exe__Infer.run in file "src/infer.ml", line 21, characters 2-47
Called from IBase__Utils.timeit in file "src/base/Utils.ml", line 429, characters 16-20
Called from IBase__ScubaLogging.execute_with_time_logging in file "src/base/ScubaLogging.ml", line 79, characters 29-44
Called from Dune__exe__Infer.run in file "src/infer.ml", line 25, characters 22-94

Run the command again with `--keep-going` to try and ignore this error.
cat: infer-out/report.txt: No such file or directory
```

**Comment by matjin** [comment]
In the latest docker release you shouldn't see this issue.
